### ISSUE TITLE
ARHitTestResult WorldTransform.Row3 Not Found

### ISSUE THREAD

**Issue by acroutworst** [EgorBo/ARKitXamarinDemo#2]
Hello there!

I am working on iOS 11 Preview 8 and on Visual Studio for Mac 7.2 Preview. The Row3 property seems to be missing within the context of ARHitTestResult WorldTransform. An example of this can be found in ArkitApp.cs on line 238. Any help would be appreciated!

<img width="931" alt="screenshot 2017-09-10 00 34 16" src="https://user-images.githubusercontent.com/10387238/30247069-f890cd10-95bf-11e7-8fed-933eb8790602.png">

Thanks,
Adam

**Comment by beeradmoore** [comment]
It seems (I literally downloaded this 5 minutes ago so I could be way off) that result.WorldTransform is of type Simd.MatrixFloat4x4, but the .Row3 exists in OpenTK.Matrix4. Typecasting it works and I can get the demo to run, but there does not appear to be anything output so I don't think the solution is to typecast it.

**Comment by acroutworst** [comment]
@ytn3rd yes, I tried typecasting to OpenTK.Matrix4 as well and had the same result

**Comment by EgorBo** [comment]
@ytn3rd @acroutworst yea, recent XamIOS update broke my samples. But I've fixed them - should work now. (master)

**Comment by beeradmoore** [comment]
Hmm, using latest [preview 9](https://releases.xamarin.com/preview-xcode-9-gm-ios-11-support-preview-9/) with Xcode GM I still had to typecast some things and managed to get some 3D models to appear although the view appears inverted. Turning phone around I managed to get a mutant dancing on my desktop (even though the status text in top right as well as main menu is upside down).

Am going to fork and play with it tonight now that something is appearing at least :) Cheers for getting that sorted.

**Comment by edwardyehuang** [comment]
Still not work. 
Cannot found "Column3", at same line in this issue, from latest commit
![image](https://user-images.githubusercontent.com/3354448/30467529-815736cc-9a28-11e7-94b8-a0b9dedaf379.png)

**Comment by beeradmoore** [comment]
@zgszft , I've fixed the typecast issues in a fork repo over [here](https://github.com/ytn3rd/ARKitXamarinDemo). I don't know enough about ARKit or Urho, but one of the scenes is upside down. So the mutant demo works but only if I hold my device in landscape left, while the menu and on screen text display is landscape right.

**Comment by EgorBo** [comment]
@ytn3rd @zgszft oh I guess you need a more recent Xamarin.iOS version
try this one: https://bosstoragemirror.azureedge.net/wrench/macios-mac-xcode9/15/152b654a628e4ea0e6afe8a638a0bada1f3f4be4/xamarin.ios-11.0.0.0.pkg (https://jenkins.mono-project.com/view/Xamarin.MaciOS/job/xamarin-macios-builds-xcode9/)

**Comment by beeradmoore** [comment]
Just tested this on stable release everything (Xcode, iOS11, VS) that was fully released today and still have the upside down behaviour.
